version: '3.9'
services:
  node-nvidia-smi-realtime-stats:
    container_name: node-nvidia-smi-realtime-stats
    image: node:21.7-bookworm
    restart: unless-stopped
    environment:
      PORT: 2080
    build:
      context: .
    user: node
    working_dir: /home/node/app
    ports:
      - 2080:2080
    command: "npm start"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
